### ISSUE TITLE
SSL error even with IGNORE_SSL_ERRORS=True

### ISSUE THREAD

**Issue by silvioruppe** [netbox-community/Device-Type-Library-Import#83]
I'm getting this trace below if I try to import the device type library. Netbox system is using an certificate issued by DigiCert not a self signed certificate. How can I solve the issue? Thank you!

Pulled Repo https://github.com/netbox-community/devicetype-library.git
IGNORE_SSL_ERRORS is True, catching exception and disabling SSL verification.
Traceback (most recent call last):
  File "C:\Users\103925siru\.conda\envs\netbox_import\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\103925siru\.conda\envs\netbox_import\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\103925siru\.conda\envs\netbox_import\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\103925siru\.conda\envs\netbox_import\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\103925siru\.conda\envs\netbox_import\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\103925siru\.conda\envs\netbox_import\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\103925siru\.conda\envs\netbox_import\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\103925siru\.conda\envs\netbox_import\lib\ssl.py", line 1041, in _create
    self.do_handshake()
  File "C:\Users\103925siru\.conda\envs\netbox_import\lib\ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

**Comment by danner26** [comment]
Hey @silvioruppe is this in the master or are you using the beta branch?
